# Generated by Django 4.2.6 on 2023-10-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postrouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing', models.CharField(max_length=10)),
                ('source_ip', models.CharField(max_length=18)),
                ('protocol', models.CharField(max_length=3)),
                ('destination_ip', models.CharField(max_length=18)),
                ('destination_port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='prerouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing', models.CharField(max_length=10)),
                ('source_ip', models.CharField(max_length=18)),
                ('source_port', models.IntegerField()),
                ('protocol', models.CharField(max_length=3)),
                ('destination_ip', models.CharField(max_length=18)),
                ('destination_port', models.CharField(max_length=3)),
            ],
        ),
    ]
