# Generated by Django 4.2.6 on 2023-10-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_fetcher_display', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postrouting',
            name='destination_port',
        ),
        migrations.RemoveField(
            model_name='postrouting',
            name='protocol',
        ),
    ]
