# Generated by Django 4.1 on 2023-10-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_fetcher_display', '0002_remove_postrouting_destination_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerouting',
            name='source_port',
            field=models.CharField(max_length=6),
        ),
    ]
