# Generated by Django 4.1 on 2023-10-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_fetcher_display', '0004_userprofileinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofileinfo',
            options={'permissions': [('view_article', 'Can view article'), ('edit_article', 'Can edit article')]},
        ),
    ]
