# Generated by Django 4.1 on 2023-10-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_fetcher_display', '0006_alter_userprofileinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofileinfo',
            options={'permissions': [('view', 'Can view page'), ('edit', 'Can edit pages')]},
        ),
    ]
