# Generated by Django 4.1 on 2023-11-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_fetcher_display', '0008_serverdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdetails',
            name='ip',
            field=models.CharField(max_length=20),
        ),
    ]
