# Generated by Django 4.1 on 2023-11-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_adding', '0004_alter_lastpk_prerouting_last_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastpk',
            name='prerouting_last_pk',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
