# Generated by Django 4.1 on 2023-11-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_adding', '0005_alter_lastpk_prerouting_last_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastpk',
            name='postrouting_last_pk',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='lastpk',
            name='prerouting_last_pk',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
